### ISSUE TITLE
Quite confused

### ISSUE THREAD

**Issue by AkemiShimizu** [DreamingCoders/PHPDoge#3]
What is the purpose of this framework? Looking at it I find a lot of code from other repositories but no common objective of their use, you have CLI tools that interact with a linux system and also a routing from an MVC framework and also some PHP?

This is a whole lot of a mess and I cant really see any purpose torwards it.

Not going to try forking and "improving" because there is nothing to improve if there's no objective of product.

You smashed together random pieces of code with yours?

**Comment by DreamingCoders** [comment]
You are one of the most annoying kids I've ever had to deal with, let me ask you a question are you proud of yourself?
All you do is DDoS websites and SMS spam, you've already been reported for doing so.
I'm giving a tool for users, something you could never do, you make fake resumes claiming you work for the "Down" Jones which never exists, you make multiple identities because your personality is always shifting, true programmers actually do work instead of cause problems
https://vocaroo.com/12rgNdilwE3J
I wonder how it feels. You must have a lot of sorrow in your life. Issue closed.
